# Generated by Django 5.0.1 on 2024-04-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='goals_stats',
            field=models.JSONField(null=True),
        ),
    ]
