# Generated by Django 5.0.1 on 2024-04-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_match_goals_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='api_football_id',
            new_name='id_api_football',
        ),
    ]
