# Generated by Django 5.0.1 on 2025-01-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_match_temporary_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='temporary_team_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Поле для хранения временного ID от АПИ'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('NS', 'Не начался'), ('FT', 'Завершен'), ('1H', 'Идет первый тайм'), ('HT', 'Перерыв'), ('2H', 'Идет второй тайм'), ('CANC', 'Отменен'), ('PEN', 'Серия пенальти'), ('TBD', 'Точная дата не известна'), ('PST', 'Отложен'), ('INT', 'Прерван')], default='NS', max_length=5, verbose_name='Статус матча'),
        ),
    ]
