# Generated by Django 5.0.1 on 2024-04-23 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_rename_api_football_id_team_id_api_football'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Событие')),
                ('description', models.TextField(blank=True, verbose_name='Описание события')),
                ('operation', models.CharField(choices=[('A', 'Добавить'), ('R', 'Отнять'), ('N', 'Не менять')], default='N', max_length=1, verbose_name='Операция')),
                ('value', models.IntegerField(default=0)),
                ('tour', models.IntegerField(default=0)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='tournaments.team', verbose_name='Команда')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournaments.tournament', verbose_name='Турнир')),
            ],
        ),
    ]
