# Generated by Django 5.0.1 on 2024-04-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AddField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/tournaments/'),
        ),
    ]
