# Generated by Django 5.0.1 on 2024-08-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_alter_apifootballid_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apifootballid',
            options={'verbose_name': 'Соответствия APIFootball', 'verbose_name_plural': 'Соответствие APIFootball'},
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('NS', 'Не начался'), ('FT', 'Завершен'), ('1H', 'Идет первый тайм'), ('HT', 'Перерыв'), ('2H', 'Идет второй тайм'), ('CANC', 'Отменен'), ('PEN', 'Серия пенальти'), ('TBD', 'Точная дата не известна'), ('PST', 'Отложен')], default='NS', max_length=5, verbose_name='Статус матча'),
        ),
    ]
