# Generated by Django 5.0.1 on 2024-10-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_apifootballid_options_alter_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id_api_football',
            field=models.BigIntegerField(blank=True, db_index=True, default=0, verbose_name='ID на Api Football'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id_api_football',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='ID на API Football'),
        ),
    ]
