# Generated by Django 5.0.1 on 2024-10-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_alter_match_id_api_football_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='id_api_football',
        ),
    ]
